### ISSUE TITLE
文件排序界面能否增加一个时间排序

### ISSUE THREAD

**Issue by jzysl123** [iwestlin/gdshare#10]
名称	类型         大小
目前只有三个

可以加个代码 设置默认打开团队盘的排序方式是按哪个排序

**Comment by iwestlin** [comment]
已实现：
https://github.com/iwestlin/gdshare/blob/3be9b61d9189679a89584b95875ba82109377655/template.js#L6
由于Google API不支持根据size排序，所以现在只支持根据修改时间或文件名排序，同时可选是否逆序排列。
