### ISSUE TITLE
能增加在線播放功能嗎

### ISSUE THREAD

**Issue by kai456789** [iwestlin/gdshare#11]
看到https://github.com/Aicirou/goindex-theme-acrou

有此功能 不知道能不能也加入

**Comment by iwestlin** [comment]
可以是可以，实现很简单，就是一个video标签`<video src="..."></video>`

但我看不出来用浏览器播放的好处，首先它效率比较低，其次浏览器对各种音视频的编码支持不是很完善，有些视频无法播放，有些视频则没有声音，也没办法加载字幕。

现在各个系统都有很优秀的视频播放器，项目也支持调用这些播放器播放：
Windows有potplayer，mac有IINA，安卓有MXPlayer，iOS有nPlayer

**Comment by kai456789** [comment]
> 可以是可以，实现很简单，就是一个video标签`<video src="..."></video>`
> 
> 但我看不出来用浏览器播放的好处，首先它效率比较低，其次浏览器对各种音视频的编码支持不是很完善，有些视频无法播放，有些视频则没有声音，也没办法加载字幕。
> 
> 现在各个系统都有很优秀的视频播放器，项目也支持调用这些播放器播放：
> Windows有potplayer，mac有IINA，安卓有MXPlayer，iOS有nPlayer

好的 就方便觀看 支援性不是很高就是

**Comment by wang001200** [comment]
> 可以是可以，实现很简单，就是一个video标签`<video src="..."></video>`
> 
> 但我看不出来用浏览器播放的好处，首先它效率比较低，其次浏览器对各种音视频的编码支持不是很完善，有些视频无法播放，有些视频则没有声音，也没办法加载字幕。
> 
> 现在各个系统都有很优秀的视频播放器，项目也支持调用这些播放器播放：
> Windows有potplayer，mac有IINA，安卓有MXPlayer，iOS有nPlayer

想要，如果简单又不影响其他的话，加一下把。毕竟有些格式也能直接播放，调用系统的还是多了几个步骤
