### ISSUE TITLE
好像调用播放器不起作用?

### ISSUE THREAD

**Issue by vvlaw** [iwestlin/gdshare#13]
点击后,浏览器会出现potplayer:// 或者vlc:// 等链接,但是不会自动打开app来进行播放.

wind10下面的potplayer和vcl都试过了.

iOS下面的nplayer可以自动调用

**Comment by iwestlin** [comment]
我手边没windows机器，没法测试potplayer，不过有人反映没问题的（最新代码）：https://github.com/iwestlin/gdshare/issues/2#issuecomment-672439169
你可以检查下软件设置，也可能是杀毒软件拦截之类的

我测试过 mxplayer(free)，iina和nplayer，都可以

**Comment by vvlaw** [comment]
我又重新下载了个exe来安装potplayer,现在浏览器会弹出要不要调用potplayer来播放.

现在可以了,不过vcl我也u是用安装版的,但是确不会弹出跳转.不过,现在已经可以用了,非常好用.

**Comment by iwestlin** [comment]
https://github.com/stefansundin/vlc-protocol/blob/master/windows/README.md
这里有各个系统的 `vlc://` 唤起解决方案
