### ISSUE TITLE
CloudFlare 一直以我的域名缓存了非HTML的内容而直接暂停我的CloudFlare

### ISSUE THREAD

**Issue by samleong123** [iwestlin/gdshare#19]
我有一个空的域名，什么都没有空空的域名，然后给它加上您的GDShare 后，只要大量下载（超过200GB) ，我的域名直接被暂停计划：
![image](https://user-images.githubusercontent.com/58818070/90617117-e2424680-e240-11ea-8773-bdb0e8f60054.png)
询问了客服回答是由于缓存了非HTML的内容违反了CloudFlare TOS，要等待7天恢复
![image](https://user-images.githubusercontent.com/58818070/90617322-21709780-e241-11ea-8868-a6e4409a7165.png)
之前使用GDIndex 没有这样子的问题，利用了GDShare就出事了，请问可以修复一下吗？感谢大佬！

**Comment by iwestlin** [comment]
> ...including the storage, caching or **proxying** of...

gdshare 没有缓存非HTML的内容，而是相当于一个代理下载了Google drive的文件。

你被封和你用什么工具没有关系，而是因为你把链接分享给了几万人的频道：https://t.me/gdurl/9192

如果希望这个工具大家都能用得久一点，就不要做这种明显违反Tos的事情了……

我自己使用和小范围的分享是没遇到过问题的。
