### ISSUE TITLE
视频文件获取直链后添加按钮 直接调用在potplayer nplayer 打开

### ISSUE THREAD

**Issue by jzysl123** [iwestlin/gdshare#2]
就不需要获取直链再到播放器里面粘贴播放了
https://github.com/Aicirou/goindex-theme-acrou 类似这个的功能 直接调用播放器打开直链

**Comment by github-plus** [comment]
大佬什么时候出这个功能

**Comment by iwestlin** [comment]
估计周末吧

**Comment by github-plus** [comment]
期待大佬的更新

**Comment by luceng** [comment]
> 估计周末吧

大佬不更了吗？

**Comment by iwestlin** [comment]
已实现 https://github.com/iwestlin/gdshare#2020-08-12

**Comment by github-plus** [comment]
第一时间用上了

**Comment by github-plus** [comment]
> 已实现 https://github.com/iwestlin/gdshare#2020-08-12
> 
> 需要在cloudflare workers中手动更新下 [template.js](https://github.com/iwestlin/gdshare/blob/master/template.js) 的最后一行
我在唤起potplayer的时候打开显示无法打开改文件，但是复制链接打开就可以。

**Comment by iwestlin** [comment]
我手边没windows机器，自己只测试了下 iina是可以的，估计是`encodeURIComponent`这里有问题。

我更新了下代码，你再试试看？

**Comment by github-plus** [comment]
可以了，谢谢大佬

**Comment by psychopasss** [comment]
大佬，你的分享功能很不错，不过 goindex-theme-acrou 这个的UI更好，如果有时间可以整合到里面就完美了。

**Comment by wgjj** [comment]
大佬，直接在线播放不打算更新下吗
