### ISSUE TITLE
近期发现一个BUG：输入某些特定关键字进行搜索后网页会变白屏（看上去像是跳转失败）

### ISSUE THREAD

**Issue by kingofotaku** [iwestlin/gdshare#28]
RT 举两个关键词：秘密森林、前男友 无论是一次性输入这两个关键词进行搜索，还是先输入其中一部分进行搜索后再补全进行二次搜索，均会出现跳转失败的情况。目前我还没用其他账号做测试，无法确定该情况是否与特定账号配置有关系。

**Comment by iwestlin** [comment]
我自己搜这两个是没问题的，你可以打开网页控制台看看具体什么报错

**Comment by kingofotaku** [comment]
![image](https://user-images.githubusercontent.com/12953574/94987324-3e1a2200-0598-11eb-9e0c-b5af544d5d4f.png)
获得信息如上

**Comment by iwestlin** [comment]
看上去是有些文件没有 parents 这个属性导致的。
因为代码里调用了 `parents[0]` 获取文件的父目录，而 parents 是 `undefined` 时就会报错。
正常所有文件都会有这个属性的，不知道你搜出了什么奇怪的东西……可以的话看看控制台network一栏`search`这个网络请求具体返回了什么。

我刚提交了一个新的前端版本 `20201003.js` ，兼容了parents为undefined的情况，你可以替换掉之前的 `20200827.js` 试试。

**Comment by kingofotaku** [comment]
替换时发生错误
![image](https://user-images.githubusercontent.com/12953574/94987665-8d615200-059a-11eb-8a45-7801eb43bef8.png)

**Comment by iwestlin** [comment]
你是不是把 20201003.js里的内容复制到 template.js里了啊？

只需要把`template.js`里的 `20200827` 替换成 `20201003`的，像这里 https://github.com/iwestlin/gdshare/issues/23#issuecomment-681065317

**Comment by kingofotaku** [comment]
> 你是不是把 20201003.js里的内容复制到 template.js里了啊？
> 
> 只需要把`template.js`里的 `20200827` 替换成 `20201003`的，像这里 [#23 (comment)](https://github.com/iwestlin/gdshare/issues/23#issuecomment-681065317)

抱歉 一时间没反应过来orz

**Comment by kingofotaku** [comment]
经测试问题已解决，非常感谢！（顺便提醒一下仓库中`template.js`里的js版本还是0813-2）

**Comment by iwestlin** [comment]
我刚改好了……

> 经测试问题已解决，非常感谢！（顺便提醒一下仓库中`template.js`里的js版本还是0813-2）

**Comment by kingofotaku** [comment]
> 我刚改好了……
> 
> > 经测试问题已解决，非常感谢！（顺便提醒一下仓库中`template.js`里的js版本还是0813-2）

刚才发现我那两个关键词其中一个搜出的文件名里有`%`这个符号，说不定和这个有关系。
