### ISSUE TITLE
Can't search files/folders with  ' ( single quote ) containing text ( like X's pen, Y's pencil )

### ISSUE THREAD

**Issue by sp-555** [iwestlin/gdshare#29]

**Comment by iwestlin** [comment]
Thank you for your report, it been fixed.

For the record, I just added a line after `e&&(s.pageToken=e),`

```js
t=t.replace(/'/g, "\\'"),
```

**Comment by iwestlin** [comment]
There are still some problems that I can't find solution in https://developers.google.com/drive/api/v3/search-files:

- If only search `'`, it will get all files.
- If only search '"`, it will throw an error.
- If there are two files `"Jack" son` and `Jackson`, search `Jack"` will get them all...seems like google will ignore `"` character
