### ISSUE TITLE
#6d4d3eb 个人盘无法访问

### ISSUE THREAD

**Issue by xinxin8816** [iwestlin/gdshare#38]
请求个人盘 https://xxx.workers.dev/ls/root 会跳转到 https://xxx.workers.dev/ls/undefined
然后耗尽请求额度或浏览器崩溃

**Comment by iwestlin** [comment]
多谢反馈，已经推送修复版，jsdelivr可能需要1天时间才会更新cdn缓存，如果需要立即见效可以将 `template.js` 中的 `20210227.js` 改成 `20210304.js`

**Comment by iwestlin** [comment]
这个问题出现的原因是上次提交中我加入了打开文件夹自动获取其整体路径的功能。

可是没想到 对于个人盘的顶层路径（也就是/ls/root），请求其父目录竟然也会返回一个盘符，间接导致了死循环不断请求。

修复方法是如果监测到当前路径为 `/ls/root` 则不获取其整体路径。
