### ISSUE TITLE
搭建好之后搜索不到文件

### ISSUE THREAD

**Issue by GJKen** [iwestlin/gdshare#4]
已经将脚本的里需要变量id写好了,不知道为什么搜索不到文件

**Comment by iwestlin** [comment]
https://github.com/iwestlin/gd-utils#%E4%B8%AA%E4%BA%BA%E5%B8%90%E5%8F%B7%E9%85%8D%E7%BD%AE
你可以根据这一节来检查个人授权信息配置是否有效

**Comment by github-plus** [comment]
应该是你的refresh没写对，我最初也是这样

**Comment by HYQ307** [comment]
遇到同样的问题，直接复制的rclone里的refrest_token等相关变量，rclone lsf可以显示目录；
