### ISSUE TITLE
希望能加入批量提取直链

### ISSUE THREAD

**Issue by kolicime** [iwestlin/gdshare#6]
文件多的时候一个一个复制有些繁琐

**Comment by iwestlin** [comment]
如果有需要的人很多的话我会考虑实现。

当前如果有下载大量文件的需求可以使用 https://github.com/iwestlin/gd-utils/blob/master/changelog.md#2020-08-05
适合下载整个目录并保留目录结构。

**Comment by kolicime** [comment]
配合百宝箱用确实也不错，不过如果是分享给别人的话对方应该是没有gd-utils的。这个功能在大佬tg那条消息的评论区呼声还是挺高的

**Comment by carlliuxx** [comment]
求批量获取功能～～～

**Comment by haobanz** [comment]
铜球

**Comment by iwestlin** [comment]
已实现 https://github.com/iwestlin/gdshare#2020-08-12
