### ISSUE TITLE
请问目前可以添加多个账号吗？

### ISSUE THREAD

**Issue by kingofotaku** [iwestlin/gdshare#7]
如题

**Comment by iwestlin** [comment]
不同帐号有不同的搜索结果，对不同的目录有不同的权限，你是想把它们合在一起？

可以建两个worker，分别填入不同帐号的信息啊

**Comment by kingofotaku** [comment]
> 不同帐号有不同的搜索结果，对不同的目录有不同的权限，你是想把它们合在一起？
> 
> 可以建两个worker，分别填入不同帐号的信息啊

确实，是我考虑不周。感谢提醒。
