### ISSUE TITLE
复制的所有文件都559b？

### ISSUE THREAD

**Issue by carlliuxx** [iwestlin/gdshare#8]
![image](https://user-images.githubusercontent.com/52060495/89544074-44a84980-d834-11ea-834f-a2d26885ef86.jpeg)

能下载～
请问这三个参数应该填什么？

folderID
这个是共享文件夹的Google id？

-k 'your hashkey' 
这个是共享文件夹的密码？

-c 'your.domain.com'
这个是文件夹共享的地址？

对么？

**Comment by iwestlin** [comment]
hashkey是 https://github.com/iwestlin/gdshare/blob/43e2c5bc0dd9184606bfa12afce0c590355bf22a/template.js#L3
用来给下载链接签名的

生成的链接用浏览器直接下载的文件正常么？
aria2c下载的文件不正常？你直接执行 `aria2c '生成的链接'`能下么

**Comment by iwestlin** [comment]
`your.domain.com`是你的cloudflare worker的域名，类似 `fragrant-tree-j3h4.aaa.workers.dev` 这种

**Comment by carlliuxx** [comment]
搞定了～之前hashkey填错了，谢谢～～～
