### ISSUE TITLE
下载ass字幕文件会变成mp3的后缀名

### ISSUE THREAD

**Issue by upupoo18** [iwestlin/gdshare#9]
不知可否修改为正常的后缀名？
另外，问一下有人知道potplayer调用远程字幕的方法吗？
还希望大佬可以出一个团队盘目录，输入ID实在有些麻烦
（感谢大佬的付出！！！）

**Comment by iwestlin** [comment]
> 希望大佬可以出一个团队盘目录，输入ID实在有些麻烦

**Comment by iwestlin** [comment]
我试了下chrome浏览器下载 `.ass`的文件会自动改成 `.txt`，不过其中内容是一样的，手动重命名下就行了。

我试了下aria2c，下载的文件名和原始文件名一致，可能浏览器有什么特殊处理吧

**Comment by iwestlin** [comment]
我刚更新了下代码，应该修复了文件名不一致的问题，你可以更新试试。

如果还是被重命名，注意下是不是下载被浏览器的扩展程序劫持了，我使用chrome原生的下载功能没问题

**Comment by iwestlin** [comment]
<img width="620" alt="截屏2020-08-12 下午8 39 21" src="https://user-images.githubusercontent.com/6235509/90017335-f5ec2b00-dcdd-11ea-8977-5ee7d3871009.png">

最新代码会在首页展示团队盘列表了，点击对应名称即可进入

**Comment by upupoo18** [comment]
> <img alt="截屏2020-08-12 下午8 39 21" width="620" src="https://user-images.githubusercontent.com/6235509/90017335-f5ec2b00-dcdd-11ea-8977-5ee7d3871009.png">
> 
> 最新代码会在首页展示团队盘列表了，点击对应名称即可进入

ass下载的后缀恢复正常了，索引也有了，感谢♪(･ω･)ﾉ
